### ISSUE TITLE
Device is unauthorized

### ISSUE THREAD

**Issue by red-avtovo** [butomo1989/docker-android#87]
Latest emulator doesn't provide debugging option enabled by default, which doesn't allow to run automation on Android 7.x

Operating System: 
Debian 9

Docker Image:
butomo1989/docker-android-x86-7.1.1

Docker Version:  
18.03.1-ce, build 9ee9f40

Docker Command to start docker-android:  
```
docker run -d \
	--privileged \
	--restart=unless-stopped \
	--link selenium-hub:hub \
	-p 6080:6080 \
	-p 4724:4723 \
	-e DEVICE="Nexus 5" \
	-e APPIUM=True \
	-e CONNECT_TO_GRID=True \
	-e APPIUM_HOST="ip" \
	-e SELENIUM_HOST="hub" \
	-e APPIUM_PORT=4724 \
	-e SELENIUM_PORT=4444 \
	-e MOBILE_WEB_TEST=True \
	-e BROWSER=chrome \
	--name android-container711 \
	butomo1989/docker-android-x86-7.1.1
  ```
## Expected Behavior
Device is authorized or at least asking for authorization, like on android 8.x images

## Actual Behavior
![image](https://user-images.githubusercontent.com/10682826/42379101-fe1249d4-8129-11e8-89f8-6fc1dcf1d950.png)

**Comment by butomo1989** [comment]
I think it is possible to do it manually under Developer Option @red-avtovo , but yes, we need to automate it somehow.

**Comment by red-avtovo** [comment]
I'm digging in it and I really hope, that this is just 1 argument to avd creation or emulator starting

**Comment by diemol** [comment]
I bumped into the same issue some weeks ago, the root cause is because when the emulator is using Google Play Services it assumes that it is a "production build", so no root access is possible.

To install apps and so on, adb uses the common mechanism of private and public keys. And this error pops up when the emulator does not have the public key of the adb server.

The way I fixed it in our project was to do "adb devices" before starting the emulator. This is implicitly starting the adb server and generating the keys before the emulator is started, and when the emulator starts it will have the adb server keys.

That is what needs to be automated in order to have it working.

**Comment by red-avtovo** [comment]
Will try that! Thank @diemol

**Comment by red-avtovo** [comment]
@diemol that would be super easy, but it didn't work. I see the keys, but emulator doesn't know about them.

**Comment by red-avtovo** [comment]
I solved an issue by starting emulator with `-wipe-data` flag.

**Comment by butomo1989** [comment]
Hi @red-avtovo ,

Could you create a PR for it? It would be great.

**Comment by diemol** [comment]
ah ok, the `adb devices` thing works when the AVD has not been created yet, which is the approach I was using (and I omitted that part).

Your solution seems pretty good as well, I didn't think about it :) But I guess that can make the boot process slightly slower?

**Comment by red-avtovo** [comment]
I didn't make a PR yet, because I'm pretty sure, that we need this tweak just for first container run.
After container restart that would be quite annoying to loose all data.

**Comment by butomo1989** [comment]
Fixed in release [1.2](https://github.com/butomo1989/docker-android/releases/tag/1.2)

**Comment by shadow1163** [comment]
@butomo1989 @red-avtovo Hi, I can reproduce this issue using image "butomo1989/docker-android-x86-7.1.1" tag 1.2, its image id is "ace02bf9cf03". 
![docker-android-7 1 1-adb-devices](https://user-images.githubusercontent.com/8413967/42801811-7310f878-89d3-11e8-83ef-7057bec6d889.png)
Here is docker command
```
docker run --privileged --network external --ip 10.2.2.71 -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -p 4723:4723 -e DEVICE="Samsung Galaxy S6" -e APPIUM=true --name android7 butomo1989/docker-android-x86-7.1.1
```
Container logs are here.
```
2018-07-16 23:54:05,355 CRIT Supervisor running as root (no user in config file)
2018-07-16 23:54:05,371 INFO supervisord started with pid 8
2018-07-16 23:54:06,374 INFO spawned: 'xvfb' with pid 11
2018-07-16 23:54:06,375 INFO spawned: 'port-forward' with pid 12
2018-07-16 23:54:06,377 INFO spawned: 'novnc' with pid 13
2018-07-16 23:54:06,379 INFO spawned: 'openbox' with pid 14
2018-07-16 23:54:06,382 INFO spawned: 'x11vnc' with pid 15
2018-07-16 23:54:06,383 INFO spawned: 'android-screen-mirror' with pid 16
2018-07-16 23:54:06,384 INFO spawned: 'docker-appium' with pid 17
2018-07-16 23:54:06,386 INFO spawned: 'auto-recording' with pid 18
2018-07-16 23:54:06,892 INFO success: android-screen-mirror entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-07-16 23:54:06,893 INFO exited: android-screen-mirror (exit status 0; expected)
2018-07-16 23:54:07,600 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-07-16 23:54:07,600 INFO success: port-forward entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-07-16 23:54:07,600 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-07-16 23:54:07,600 INFO success: openbox entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-07-16 23:54:07,600 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-07-16 23:54:07,600 INFO success: docker-appium entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-07-16 23:54:07,600 INFO success: auto-recording entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-07-16 23:54:12,896 INFO exited: auto-recording (exit status 0; expected)
```
Could you help to confirm it, please?

**Comment by JoeSSS** [comment]
yeah, the issue strikes back..

**Comment by JoeSSS** [comment]
@red-avtovo @butomo1989 can you please reopen the issue? The issue is still there on the playstore image. Tried to fix it in the several ways today but I'm out of ideas, need new sources :))

**Comment by red-avtovo** [comment]
@butomo1989 please open this issue
@JoeSSS @shadow1163 I will try to fix it tomorrow

**Comment by JoeSSS** [comment]
Do you have ideas? Interesting is that:
a) This doesn't happen when you access emulator from the inside of container. It happens only on `adb start-server` from outside the container
b) Clicking remember checkbox doesn't really help. After `adb kill-server && adb start-server` it will request the access again.. I thought that it can be related to adbkey from .android and copied it over to local linux machine but it also didn't work

**Comment by butomo1989** [comment]
Sorry guys @red-avtovo @JoeSSS @shadow1163 , I have a visit until end of next week so I cannot help :(

**Comment by red-avtovo** [comment]
@JoeSSS oh, that happens, because you are not sharing the same Android key with container.
Right after we create the container, we generate new identity and then newly created emulator remembers the key of his creator.
My fix did not imply the case, when you try to access the emulator from outside of container

**Comment by JoeSSS** [comment]
so, you must run tests inside the container? I use it from running Calabash tests and they are outside.

**Comment by red-avtovo** [comment]
Would be good if you will try to use the container as a Grid node. It will proxy all requests through Appium server and eventually execute all commands on container locally

**Comment by red-avtovo** [comment]
@shadow1163 do you try to connect to emulator through exposed port outside of container?

**Comment by JoeSSS** [comment]
I mean, I may be able to workaround it by just including my tests to the container and just run them inside. But I think that [this guy](https://github.com/butomo1989/docker-android/blob/master/src/port_forward.sh) will still trigger adb from outside to get acces + I believe that there are situations when people just want to use the emulator from local :)

**Comment by JoeSSS** [comment]
do you think that it is possible to do something here? for example using a key for both envs

**Comment by red-avtovo** [comment]
Then you should run your container with passing directory sharing option:
```
docker run ... -v <local Android key directory>:/root/.android/
```
Your local Android key should already be here: `~/.android`
After first run of the container, the new emulator instance will be created with your own key and it will solve the issue

**Comment by JoeSSS** [comment]
I will try it tomorrow when I have access to my laptop :) Thanks a lot @red-avtovo

**Comment by shadow1163** [comment]
@red-avtovo I have tried to connect Android on remote machine, the result is same.
```
    if not is_initialized():
        cmd = 'emulator/emulator @{name} -gpu off -verbose -wipe-data'.format(name=avd_name)
    else:
        cmd = 'emulator/emulator @{name} -gpu off -verbose'.format(name=avd_name)
```
I checked the source code, the cmd string always be not include flag "-wipe-data", does it?

**Comment by red-avtovo** [comment]
@JoeSSS what are your findings? Did you find time to verify proposed solution?

**Comment by shadow1163** [comment]
The container was run first time, the line app.py line 203 has created file "/root/init", so the line 210 should always return false.

**Comment by JoeSSS** [comment]
@red-avtovo not yet, was busy yesterday. Checking it now

**Comment by shadow1163** [comment]
I created a PR, please help to review it, thanks very much. @red-avtovo @butomo1989
